### ISSUE TITLE
VIO in ros noetic

### ISSUE THREAD

**Issue by Carlosmct** [Auterion/VIO#26]
Hello Everyone. Dear Community.
I wanted to use the package in ros noetic.  When I tried to compile it, I could not get it to compile correctly. Any suggestions?
Thanks.

**Comment by Jaeyoung-Lim** [comment]
@Carlosmct Please share the exact log of your failure

**Comment by Carlosmct** [comment]
Profile:                     default
Extending:                   None
Workspace:                   /home/dronomy/VIO_ws
---------------------------------------------------------
Build Space:        [exists] /home/dronomy/VIO_ws/build
Devel Space:        [exists] /home/dronomy/VIO_ws/devel
Install Space:      [unused] /home/dronomy/VIO_ws/install
Log Space:          [exists] /home/dronomy/VIO_ws/logs
Source Space:       [exists] /home/dronomy/VIO_ws/src
DESTDIR:            [unused] None
---------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
---------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
---------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
---------------------------------------------------------


---------------------------------------------------------
WARNING: Your workspace is not extending any other
result space, but it is set to use a `linked` devel
space layout. This requires the `catkin` CMake package
in your source space in order to be built.
---------------------------------------------------------

[build] Found '1' packages in 0.0 seconds.                                     
[build] Package table is up to date.                                           
Warning: generated devel space setup files have been deleted.
Starting  >>> catkin_tools_prebuild                                            
___________________________
Errors     << catkin_tools_prebuild:cmake /home/dronomy/VIO_ws/logs/catkin_tools_prebuild/build.cmake.001.log
CMake Warning (dev) at CMakeLists.txt:2 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

Traceback (most recent call last):
  File "/home/dronomy/VIO_ws/build/catkin_tools_prebuild/catkin_generated/generate_cached_setup.py", line 12, in <module>
    from catkin.environment_cache import generate_environment_script
ModuleNotFoundError: No module named 'catkin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dronomy/VIO_ws/build/catkin_tools_prebuild/catkin_generated/generate_cached_setup.py", line 20, in <module>
    from catkin.environment_cache import generate_environment_script
ModuleNotFoundError: No module named 'catkin'
CMake Error at /opt/ros/noetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python
  "/home/dronomy/VIO_ws/build/catkin_tools_prebuild/catkin_generated/generate_cached_setup.py")
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/all.cmake:208 (safe_execute_process)
  /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:4 (find_package)


cd /home/dronomy/VIO_ws/build/catkin_tools_prebuild; catkin build --get-env catkin_tools_prebuild | catkin env -si  /usr/bin/cmake /home/dronomy/VIO_ws/build/catkin_tools_prebuild --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/dronomy/VIO_ws/devel/.private/catkin_tools_prebuild -DCMAKE_INSTALL_PREFIX=/home/dronomy/VIO_ws/install; cd -
...............................................................................
Failed     << catkin_tools_prebuild:cmake          [ Exited with code 1 ]      
Failed    <<< catkin_tools_prebuild                [ 0.4 seconds ]             
Abandoned <<< px4_realsense_bridge                 [ Unrelated job failed ]    
[build] Summary: 0 of 2 packages succeeded.                                    
[build]   Ignored:   None.                                                     
[build]   Warnings:  None.                                                     
[build]   Abandoned: 1 packages were abandoned.                                
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 0.4 seconds total.

**Comment by Jaeyoung-Lim** [comment]
@Carlosmct Your failures are not related to rosnoetic support. As you can see in your log, catkin doesn't exist in your path
